CREATE DATABASE tcs;

USE `tcs`;

DROP TABLE IF EXISTS `TBL_USER_INFO`;

CREATE TABLE `TBL_USER_INFO` (
  `USER_ID` INT (10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `USER_NAME` VARCHAR (40) NOT NULL ,
  `USER_PW` VARCHAR (40) NOT NULL ,
  `BUSINESS_LEVEL` INT NOT NULL,
  PRIMARY KEY (`USER_ID`)
)ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `TBL_USER_EXT`;

CREATE TABLE `TBL_USER_EXT` (
  `USER_ID` INT (10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `EMAIL` VARCHAR (40) NOT NULL ,
  `TRAVEL_TIMES` INT (10) NOT NULL DEFAULT 0,
  `TOTAL_KM` INT (10),
  `PHONE_NUMBER` INT (10),
  PRIMARY KEY (`USER_ID`),
  CONSTRAINT `fk_USER_EXT_USER_INFO_OPTION1` FOREIGN KEY (`USER_ID`) REFERENCES `TBL_USER_INFO` (`USER_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
)ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `TBL_TRAVEL_PLAN`;

CREATE TABLE `TBL_TRAVEL_PLAN` (
  `TRAVEL_PLAN_ID` INT (10) UNSIGNED NOT NULL AUTO_INCREMENT ,
  `USER_ID` INT (10) UNSIGNED NOT NULL ,
  `TITLE` VARCHAR (40) NOT NULL ,
  `STATUS` INT (2) NOT NULL ,
  `DESCRIPTION` VARCHAR (200),
  `IMG_PATH` VARCHAR (200),
  PRIMARY KEY (`TRAVEL_PLAN_ID`),
  CONSTRAINT `fk_TRAVEL_PLAN_USER_INFO_OPTION1` FOREIGN KEY (`USER_ID`) REFERENCES `TBL_USER_INFO` (`USER_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
)ENGINE =InnoDB AUTO_INCREMENT =8 DEFAULT CHARSET =utf8;

DROP TABLE IF EXISTS `TBL_VIEW_POINT`;

CREATE TABLE `TBL_VIEW_POINT`(
  `VIEW_POINT_ID` INT (10) UNSIGNED NOT NULL AUTO_INCREMENT ,
  `USER_ID` INT (10) UNSIGNED NOT NULL ,
  `NODE_TEXT` VARCHAR (40) ,
  `LATITUDE` DOUBLE ,
  `LONGITUDE` DOUBLE ,
  `DESCRIPTION`VARCHAR (200),
  PRIMARY KEY (`VIEW_POINT_ID`),
  CONSTRAINT `FK_VIEW_POINT_USER_INFO_OPTION1` FOREIGN KEY (`USER_ID`) REFERENCES `TBL_USER_INFO` (`USER_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
)ENGINE =InnoDB AUTO_INCREMENT =8 DEFAULT CHARSET =utf8;

DROP TABLE IF EXISTS `TBL_TRAVEL_FLOW`;

CREATE TABLE `TBL_TRAVEL_FLOW`(
  `TRAVEL_FLOW_ID` INT (10) UNSIGNED NOT NULL AUTO_INCREMENT ,
  `TRAVEL_PLAN_ID` INT (10) UNSIGNED NOT NULL ,
  `VIEW_POINT_ID`INT (10) UNSIGNED NOT NULL ,
  `PID` INT (10) NOT NULL ,
  `CID` INT (10) NOT NULL ,
  PRIMARY KEY (`TRAVEL_FLOW_ID`),
  CONSTRAINT `fk_TRAVEL_FLOW_TRAVEL_PLAN_OPTION1` FOREIGN KEY (`TRAVEL_PLAN_ID`) REFERENCES `TBL_TRAVEL_PLAN` (`TRAVEL_PLAN_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_TRAVEL_FLOW_VIEW_POINT_OPTION1` FOREIGN KEY (`VIEW_POINT_ID`) REFERENCES `TBL_VIEW_POINT` (`VIEW_POINT_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
)ENGINE =InnoDB AUTO_INCREMENT =8 DEFAULT CHARSET =utf8;

DROP TABLE IF EXISTS `TBL_TRAVEL_MEMBER`;

CREATE TABLE `TBL_TRAVEL_MEMBER`(
  `TRAVEL_MEMBER_ID` INT (10) UNSIGNED NOT NULL AUTO_INCREMENT ,
  `TRAVEL_PLAN_ID` INT (10) UNSIGNED NOT NULL ,
  `USER_ID` INT (10) UNSIGNED NOT NULL ,
  PRIMARY KEY (`TRAVEL_MEMBER_ID`),
  CONSTRAINT `fk_TRAVEL_MEMBER_TRAVEL_PLAN_OPTION1` FOREIGN KEY (`TRAVEL_PLAN_ID`) REFERENCES `TBL_TRAVEL_PLAN` (`TRAVEL_PLAN_ID`) ON DELETE  NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_TRAVEL_MEMBER_USER_INFO_OPTION1` FOREIGN KEY (`USER_ID`) REFERENCES `TBL_USER_INFO` (`USER_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
)ENGINE =InnoDB AUTO_INCREMENT =8 DEFAULT CHARSET =utf8;

DROP TABLE IF EXISTS `TBL_VIEW_POINT_IMAGE`;

CREATE TABLE `TBL_VIEW_POINT_IMAGE`(
  `VIEW_POINT_IMAGE_ID` INT (10) UNSIGNED NOT NULL AUTO_INCREMENT ,
  `IMG_PATH` VARCHAR (200) NOT NULl ,
  `VIEW_POINT_ID` INT (10) UNSIGNED NOT NULL ,
  PRIMARY KEY (`VIEW_POINT_IMAGE_ID`),
  CONSTRAINT `fk_VIEW_POINT_IMAGE_VIEW_POINT_OPTION1` FOREIGN KEY (`VIEW_POINT_ID`) REFERENCES `TBL_VIEW_POINT`(`VIEW_POINT_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
)ENGINE =InnoDB AUTO_INCREMENT =8 DEFAULT CHARSET =utf8;